build:
	gcc Assignment1_2.c -o Assignment1_2Exe
run:
	./Assignment1_2Exe ${ARGS1} ${ARGS2}
clean:
	rm Assignment1_2Exe
help_run:
	echo "Use command as make ARGS1=filename ARGS2=mode (read/write/readwrite) run."
	
