build:
	gcc Assignment1_3.c -o Assignment1_3Exe
run:
	./Assignment1_3Exe ${filename} ${mode}
clean:
	rm Assignment1_3Exe
help:
	echo "Pass command line argument as: ./executablename filename mode (read/write/execute)";
