build-packer:
	gcc packer.c -o myexepack
run-packer:
	./myexepack ${ARG}
help-packer:
	echo 'Give Command as: make ARG="folderName fileName" run'
build-unpacker:
	gcc unpack.c -o myexeunpack
run-unpacker:
	./myexeunpack ${ARG}
help-unpacker:
	echo 'Give Command as: make ARG="fileName" run'


